hub:
  image:
    name: trungleduc/k8s-hub-tljh
    tag: 3.3.7
  services:
    binder:
      url: http://binderhub-binderhub-service

config:
  BinderHub:
    use_registry: false
    base_url: /services/binder
    enable_api_only_mode: false
