jupyterhub:
  enabled: true
  hub:
    image:
      name: trungleduc/k8s-hub-tljh
      tag: 3.3.12
      pullPolicy: Always
    config:
      BinderSpawner:
        auth_enabled: true
    extraFiles:
      my_jupyterhub_config:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/jupyterhub_config.py
    networkPolicy:
      enabled: false

  proxy:
    chp:
      networkPolicy:
        enabled: false

  singleuser:
    networkPolicy:
      enabled: false

binderhub-service:
  config:
    BinderHub:
      base_url: /services/binder
      use_registry: true
      image_prefix: trungleduc/binder-
      enable_api_only_mode: true

  buildPodsRegistryCredentials:
    server: "https://index.docker.io/v1/"
